"""CLI entry points for axis-core."""

from __future__ import annotations

import argparse
import importlib
import importlib.util
import inspect
import re
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any, Final, cast

from axis_core.config import config
from axis_core.engine.registry import memory_registry, planner_registry

_ENV_ASSIGN_RE: Final[re.Pattern[str]] = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*="
)

_BUNDLES: Final[dict[str, tuple[str, str, str]]] = {
    "anthropic": ("Anthropic model adapter", "axis-core[anthropic]", "anthropic"),
    "openai": ("OpenAI model adapter", "axis-core[openai]", "openai"),
    "openrouter": ("OpenRouter compatibility adapter", "axis-core[openrouter]", "openai"),
    "redis": ("Redis memory adapter", "axis-core[redis]", "redis"),
    "sqlite": ("SQLite memory adapter", "axis-core[sqlite]", "aiosqlite"),
    "synaptic": ("Synaptic memory adapter", "axis-core[synaptic]", "synaptic_core"),
}

_MEMORY_DEPS: Final[dict[str, tuple[str, str]]] = {
    "redis": ("redis", "axis-core[redis]"),
    "sqlite": ("aiosqlite", "axis-core[sqlite]"),
    "synaptic": ("synaptic_core", "axis-core[synaptic]"),
}


def _module_available(module_name: str) -> bool:
    return importlib.util.find_spec(module_name) is not None


def _install_requirement(requirement: str) -> None:
    subprocess.run(
        [sys.executable, "-m", "pip", "install", requirement],
        check=True,
    )


def _write_env_updates(env_file: Path, updates: dict[str, str]) -> None:
    lines: list[str] = []
    if env_file.exists():
        lines = env_file.read_text(encoding="utf-8").splitlines()

    filtered: list[str] = []
    for line in lines:
        match = _ENV_ASSIGN_RE.match(line)
        if match and match.group(1) in updates:
            continue
        filtered.append(line)

    if filtered and filtered[-1].strip():
        filtered.append("")

    filtered.append("# Generated by axis-core init")
    for key, value in updates.items():
        filtered.append(f"{key}={value}")

    env_file.write_text("\n".join(filtered).rstrip() + "\n", encoding="utf-8")


def _prompt_yes_no(prompt: str, *, default: bool) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        raw = input(f"{prompt} {suffix} ").strip().lower()
        if not raw:
            return default
        if raw in {"y", "yes"}:
            return True
        if raw in {"n", "no"}:
            return False
        print("Please enter 'y' or 'n'.")


def _prompt_choice(prompt: str, choices: list[str], default: str) -> str:
    print(prompt)
    for idx, choice in enumerate(choices, start=1):
        marker = " (default)" if choice == default else ""
        print(f"  {idx}. {choice}{marker}")

    while True:
        raw = input("Select an option by number or name: ").strip().lower()
        if not raw:
            return default
        if raw.isdigit():
            value = int(raw)
            if 1 <= value <= len(choices):
                return choices[value - 1]
        for choice in choices:
            if raw == choice.lower():
                return choice
        print("Invalid selection. Try again.")


def _prompt_bundle_installs() -> list[str]:
    print("Optional adapter packages available for install:")
    for name, (description, requirement, _module) in _BUNDLES.items():
        status = "installed" if _module_available(_module) else "missing"
        print(f"  - {name}: {description} ({requirement}) [{status}]")
    print("Enter adapter names separated by commas, or press Enter to skip.")

    while True:
        raw = input("Install adapters: ").strip()
        if not raw:
            return []
        selected = [item.strip().lower() for item in raw.split(",") if item.strip()]
        invalid = [item for item in selected if item not in _BUNDLES]
        if invalid:
            print(f"Unknown adapter bundle(s): {', '.join(invalid)}")
            continue
        deduped: list[str] = []
        for item in selected:
            if item not in deduped:
                deduped.append(item)
        return deduped


def _memory_choices() -> list[str]:
    registered = set(memory_registry.list())
    registered.update({"ephemeral", "sqlite", "redis", "synaptic"})
    preferred = ["synaptic", "ephemeral", "sqlite", "redis"]
    ordered = [name for name in preferred if name in registered]
    ordered.extend(sorted(name for name in registered if name not in ordered))
    return ordered


def _planner_choices() -> list[str]:
    choices = planner_registry.list()
    if config.default_planner not in choices:
        choices = [*choices, config.default_planner]
    return sorted(set(choices))


def _install_bundles(bundle_names: list[str]) -> bool:
    for bundle_name in bundle_names:
        description, requirement, module_name = _BUNDLES[bundle_name]
        if _module_available(module_name):
            continue
        print(f"Installing {description} ({requirement})...")
        try:
            _install_requirement(requirement)
        except subprocess.CalledProcessError as exc:
            print(f"Failed to install {requirement}: {exc}")
            return False
    return True


def _ensure_memory_dependency(
    memory_name: str,
    *,
    install_missing: bool,
    interactive: bool,
) -> bool:
    dep = _MEMORY_DEPS.get(memory_name)
    if dep is None:
        return True

    module_name, install_spec = dep
    if _module_available(module_name):
        return True

    if install_missing:
        try:
            _install_requirement(install_spec)
        except subprocess.CalledProcessError as exc:
            print(f"Failed to install {install_spec}: {exc}")
            return False
        return _module_available(module_name)

    if not interactive:
        print(
            f"Selected memory adapter '{memory_name}' requires '{install_spec}'. "
            "Re-run with --install-missing or --install synaptic."
        )
        return False

    if _prompt_yes_no(
        f"Memory adapter '{memory_name}' is missing. Install {install_spec} now?",
        default=True,
    ):
        try:
            _install_requirement(install_spec)
        except subprocess.CalledProcessError as exc:
            print(f"Failed to install {install_spec}: {exc}")
            return False
        return _module_available(module_name)

    return False


def _bootstrap_synaptic_db(db_path: str) -> None:
    from axis_core.adapters.memory.synaptic import SynapticMemory

    Path(db_path).expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    SynapticMemory(db_path=db_path)


def _run_init(args: argparse.Namespace) -> int:
    interactive = not args.yes

    requested_bundles = list(args.install or [])
    if interactive and not args.skip_install_prompt:
        requested_bundles.extend(_prompt_bundle_installs())
    if requested_bundles and not _install_bundles(requested_bundles):
        return 1

    memory_choices = _memory_choices()
    if "synaptic" in memory_choices:
        memory_default = "synaptic"
    elif config.default_memory in memory_choices:
        memory_default = config.default_memory
    else:
        memory_default = "ephemeral"
    selected_memory = args.memory
    selected_memory_from_default = selected_memory is None
    if selected_memory is None and interactive:
        selected_memory = _prompt_choice(
            "Select default memory adapter:",
            memory_choices,
            default=memory_default,
        )
    if selected_memory is None:
        selected_memory = memory_default

    planner_choices = _planner_choices()
    planner_default = (
        config.default_planner if config.default_planner in planner_choices else planner_choices[0]
    )
    selected_planner = args.planner
    if selected_planner is None and interactive:
        selected_planner = _prompt_choice(
            "Select default planner adapter:",
            planner_choices,
            default=planner_default,
        )
    if selected_planner is None:
        selected_planner = planner_default

    if selected_memory not in memory_choices:
        print(
            f"Unknown memory adapter '{selected_memory}'. "
            f"Choose one of: {', '.join(memory_choices)}"
        )
        return 1

    if selected_planner not in planner_choices:
        print(
            f"Unknown planner adapter '{selected_planner}'. "
            f"Choose one of: {', '.join(planner_choices)}"
        )
        return 1

    auto_install_default_synaptic = (
        selected_memory_from_default and not interactive and selected_memory == "synaptic"
    )
    if not _ensure_memory_dependency(
        selected_memory,
        install_missing=args.install_missing or auto_install_default_synaptic,
        interactive=interactive,
    ):
        return 1

    synaptic_path = args.synaptic_db_path
    bootstrap_synaptic = args.bootstrap_synaptic_db
    if selected_memory == "synaptic":
        if synaptic_path is None:
            synaptic_path = str(Path("synaptic.db"))
            if interactive:
                raw_path = input(
                    f"Synaptic DB path [{synaptic_path}]: "
                ).strip()
                if raw_path:
                    synaptic_path = raw_path

        if interactive and not args.bootstrap_synaptic_db:
            bootstrap_synaptic = _prompt_yes_no(
                "Initialize Synaptic SQLite database now?",
                default=True,
            )

    updates: dict[str, str] = {
        "AXIS_DEFAULT_MEMORY": selected_memory,
        "AXIS_DEFAULT_PLANNER": selected_planner,
    }
    if args.model:
        updates["AXIS_DEFAULT_MODEL"] = args.model
    if selected_memory == "synaptic" and synaptic_path is not None:
        updates["AXIS_SYNAPTIC_PATH"] = synaptic_path

    env_path = Path(args.env_file)
    _write_env_updates(env_path, updates)

    if selected_memory == "synaptic" and bootstrap_synaptic and synaptic_path is not None:
        _bootstrap_synaptic_db(synaptic_path)
        print(f"Initialized Synaptic database at {synaptic_path}")

    print(f"Configuration written to {env_path}")
    for key, value in updates.items():
        print(f"  {key}={value}")

    return 0


def _agent_kwargs_from_args(args: argparse.Namespace) -> dict[str, Any]:
    kwargs: dict[str, Any] = {}
    for field_name in ("model", "planner", "memory", "system"):
        value = getattr(args, field_name, None)
        if value is not None:
            kwargs[field_name] = value
    return kwargs


def _find_pyproject(start: Path | None = None) -> Path | None:
    """Find the nearest pyproject.toml walking upward from start (or cwd)."""
    current = (start or Path.cwd()).resolve()
    for directory in (current, *current.parents):
        candidate = directory / "pyproject.toml"
        if candidate.is_file():
            return candidate
    return None


def _load_toml_file(path: Path) -> dict[str, Any]:
    """Load a TOML file using stdlib tomllib or tomli fallback on Python 3.10."""
    toml_module: Any
    try:
        toml_module = importlib.import_module("tomllib")
    except ModuleNotFoundError:
        try:
            toml_module = importlib.import_module("tomli")
        except ModuleNotFoundError as exc:
            raise RuntimeError(
                "Reading pyproject.toml requires tomllib (Python 3.11+) or tomli on Python 3.10."
            ) from exc

    with path.open("rb") as f:
        data = toml_module.load(f)
    return cast(dict[str, Any], data)


def _pyproject_agent_ref(pyproject_path: Path) -> str | None:
    """Read [tool.axis_core].agent from pyproject.toml if present."""
    data = _load_toml_file(pyproject_path)
    tool_section = data.get("tool")
    if not isinstance(tool_section, dict):
        return None
    axis_section = tool_section.get("axis_core")
    if not isinstance(axis_section, dict):
        return None
    agent_ref = axis_section.get("agent")
    if not isinstance(agent_ref, str):
        return None
    resolved = agent_ref.strip()
    return resolved or None


def _resolve_project_agent_reference(args: argparse.Namespace) -> tuple[str | None, str | None]:
    """Resolve project-bound agent reference from args and pyproject config."""
    if getattr(args, "standalone", False):
        return None, None

    explicit_ref = getattr(args, "agent_ref", None)
    if isinstance(explicit_ref, str) and explicit_ref.strip():
        return explicit_ref.strip(), "--from"

    pyproject_path = _find_pyproject()
    if pyproject_path is None:
        return None, None

    configured_ref = _pyproject_agent_ref(pyproject_path)
    if configured_ref is None:
        return None, None
    return configured_ref, str(pyproject_path)


def _load_object_from_ref(ref: str) -> Any:
    """Load an object by import reference (module:object_path)."""
    module_name, sep, object_path = ref.partition(":")
    module_name = module_name.strip()
    object_path = object_path.strip()
    if not sep or not module_name or not object_path:
        raise ValueError(
            f"Invalid agent reference '{ref}'. Expected format: <module>:<callable_or_object>."
        )

    module = importlib.import_module(module_name)
    obj: Any = module
    for attr in object_path.split("."):
        if not hasattr(obj, attr):
            raise AttributeError(
                f"Object '{object_path}' was not found in module '{module_name}'."
            )
        obj = getattr(obj, attr)
    return obj


def _invoke_agent_factory(
    factory: Callable[..., Any],
    runtime_overrides: dict[str, Any],
) -> tuple[Any, list[str]]:
    """Invoke an agent factory with runtime overrides when accepted by signature."""
    if not runtime_overrides:
        return factory(), []

    try:
        signature = inspect.signature(factory)
    except (TypeError, ValueError):
        return factory(), sorted(runtime_overrides.keys())

    accepts_kwargs = any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD
        for parameter in signature.parameters.values()
    )
    accepted: dict[str, Any]
    dropped: list[str]
    if accepts_kwargs:
        accepted = dict(runtime_overrides)
        dropped = []
    else:
        accepted = {
            key: value for key, value in runtime_overrides.items() if key in signature.parameters
        }
        dropped = sorted(key for key in runtime_overrides if key not in accepted)

    return factory(**accepted), dropped


def _validate_agent_like(agent: Any) -> None:
    """Ensure loaded object behaves like Agent for CLI runtime needs."""
    required_methods = ("run", "session")
    missing = [method_name for method_name in required_methods if not hasattr(agent, method_name)]
    if missing:
        joined = ", ".join(missing)
        raise TypeError(
            f"Resolved agent object must define methods: {joined}. "
            "Return an axis_core.Agent instance from your factory."
        )


def _make_standalone_agent(runtime_overrides: dict[str, Any]) -> Any:
    from axis_core import Agent

    return Agent(**runtime_overrides)


def _make_agent_and_metadata(args: argparse.Namespace) -> tuple[Any, dict[str, Any]]:
    runtime_overrides = _agent_kwargs_from_args(args)
    ref, source = _resolve_project_agent_reference(args)
    metadata: dict[str, Any] = {
        "mode": "standalone",
        "reference": None,
        "source": "cli defaults/env",
        "runtime_overrides": sorted(runtime_overrides.keys()),
        "dropped_overrides": [],
    }

    if ref is None:
        return _make_standalone_agent(runtime_overrides), metadata

    loaded_object = _load_object_from_ref(ref)
    if callable(loaded_object):
        agent, dropped = _invoke_agent_factory(
            cast(Callable[..., Any], loaded_object),
            runtime_overrides,
        )
    else:
        if runtime_overrides:
            raise TypeError(
                "Runtime overrides (--model/--planner/--memory/--system) "
                "require a callable project agent factory."
            )
        agent = loaded_object
        dropped = []

    _validate_agent_like(agent)
    metadata["mode"] = "project"
    metadata["reference"] = ref
    metadata["source"] = source
    metadata["dropped_overrides"] = dropped
    return agent, metadata


def _make_agent(args: argparse.Namespace) -> Any:
    agent, _metadata = _make_agent_and_metadata(args)
    return agent


def _render_result_output(result: Any) -> str:
    output_raw = getattr(result, "output_raw", "")
    if isinstance(output_raw, str) and output_raw:
        return output_raw

    output = getattr(result, "output", None)
    if output is None:
        return ""
    return str(output)


def _run_ask(args: argparse.Namespace) -> int:
    prompt = args.prompt or ""
    if prompt == "-":
        prompt = sys.stdin.read()
    if not prompt:
        prompt = sys.stdin.read()
    if not prompt.strip():
        print("Prompt is required. Pass text or pipe stdin.", file=sys.stderr)
        return 1

    try:
        agent = _make_agent(args)
        result = agent.run(prompt, timeout=args.timeout)
    except Exception as exc:
        print(f"ask failed: {exc}", file=sys.stderr)
        return 1

    if not getattr(result, "success", False):
        error = getattr(result, "error", None)
        message = str(error) if error is not None else "unknown error"
        print(f"ask failed: {message}", file=sys.stderr)
        return 1

    print(_render_result_output(result))
    return 0


def _run_chat(args: argparse.Namespace) -> int:
    try:
        agent = _make_agent(args)
        session = agent.session(id=args.session_id, max_history=args.max_history)
    except Exception as exc:
        print(f"chat setup failed: {exc}", file=sys.stderr)
        return 1

    print(f"Chat session: {session.id}")
    print("Type /exit or /quit to leave.")

    while True:
        try:
            user_input = input("you> ").strip()
        except EOFError:
            print()
            return 0
        except KeyboardInterrupt:
            print("\nExiting chat.")
            return 0

        if not user_input:
            continue

        if user_input in {"/exit", "/quit"}:
            return 0

        if user_input == "/help":
            print("Commands: /help, /exit, /quit, /session")
            continue

        if user_input == "/session":
            print(session.id)
            continue

        try:
            result = session.run(user_input, timeout=args.timeout)
        except Exception as exc:
            print(f"assistant error: {exc}", file=sys.stderr)
            continue

        if not getattr(result, "success", False):
            error = getattr(result, "error", None)
            message = str(error) if error is not None else "unknown error"
            print(f"assistant error: {message}", file=sys.stderr)
            continue

        print(f"assistant> {_render_result_output(result)}")


def _run_doctor(args: argparse.Namespace) -> int:
    try:
        agent, metadata = _make_agent_and_metadata(args)
    except Exception as exc:
        print(f"doctor failed: {exc}", file=sys.stderr)
        return 1

    print("Axis Core CLI Doctor")
    print(f"cwd: {Path.cwd()}")
    print(f"agent mode: {metadata.get('mode')}")
    print(f"agent source: {metadata.get('source')}")
    reference = metadata.get("reference")
    if reference is not None:
        print(f"agent reference: {reference}")

    runtime_overrides = metadata.get("runtime_overrides", [])
    if runtime_overrides:
        print(f"runtime overrides: {', '.join(runtime_overrides)}")
    else:
        print("runtime overrides: none")

    dropped_overrides = metadata.get("dropped_overrides", [])
    if dropped_overrides:
        print(
            "dropped overrides: "
            + ", ".join(dropped_overrides)
            + " (factory does not accept these arguments)"
        )

    for field_name in ("_model", "_planner", "_memory", "_system"):
        label = field_name.removeprefix("_")
        value = getattr(agent, field_name, None)
        print(f"{label}: {value!r}")

    return 0


def _run_session(_args: argparse.Namespace) -> int:
    print(
        "Session management commands are not implemented yet. "
        "Use 'axis-core chat --session-id <id>' for ongoing conversations."
    )
    return 0


def _add_agent_runtime_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--model", help="Model adapter name.")
    parser.add_argument("--planner", help="Planner adapter name.")
    parser.add_argument("--memory", help="Memory adapter name.")
    parser.add_argument("--system", help="System prompt.")
    parser.add_argument(
        "--from",
        dest="agent_ref",
        help="Import reference to an agent object/factory (<module>:<callable_or_object>).",
    )
    parser.add_argument(
        "--standalone",
        action="store_true",
        help="Ignore project-bound agent config and build Agent from CLI defaults/env.",
    )
    parser.add_argument("--timeout", type=float, help="Per-run timeout in seconds.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="axis-core",
        description="Axis Core command-line utilities.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init",
        help="Interactive setup for adapter installs and default configuration.",
    )
    init_parser.add_argument("--yes", action="store_true", help="Run non-interactively.")
    init_parser.add_argument(
        "--install",
        action="append",
        choices=sorted(_BUNDLES),
        default=[],
        help="Install optional adapter bundle (can be repeated).",
    )
    init_parser.add_argument(
        "--install-missing",
        action="store_true",
        help="Install the selected memory adapter dependency if missing.",
    )
    init_parser.add_argument(
        "--skip-install-prompt",
        action="store_true",
        help="Skip interactive optional-bundle prompt.",
    )
    init_parser.add_argument("--memory", help="Default memory adapter name.")
    init_parser.add_argument("--planner", help="Default planner adapter name.")
    init_parser.add_argument("--model", help="Default model adapter name.")
    init_parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to environment file to update (default: .env).",
    )
    init_parser.add_argument(
        "--synaptic-db-path",
        help="SQLite file path used when synaptic memory is selected.",
    )
    init_parser.add_argument(
        "--bootstrap-synaptic-db",
        action="store_true",
        help="Create/initialize the synaptic database during setup.",
    )

    ask_parser = subparsers.add_parser(
        "ask",
        help="Run a single, non-interactive prompt.",
    )
    ask_parser.add_argument(
        "prompt",
        nargs="?",
        help="Prompt text. Use '-' or omit to read from stdin.",
    )
    _add_agent_runtime_args(ask_parser)

    chat_parser = subparsers.add_parser(
        "chat",
        help="Start an interactive multi-turn chat session.",
    )
    _add_agent_runtime_args(chat_parser)
    chat_parser.add_argument("--session-id", help="Existing session id to resume.")
    chat_parser.add_argument(
        "--max-history",
        type=int,
        default=100,
        help="Maximum messages retained in session history.",
    )

    doctor_parser = subparsers.add_parser(
        "doctor",
        help="Show which agent source the CLI will run and effective runtime settings.",
    )
    _add_agent_runtime_args(doctor_parser)

    subparsers.add_parser(
        "session",
        help="Session management command namespace (placeholder).",
    )

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "init":
        return _run_init(args)
    if args.command == "ask":
        return _run_ask(args)
    if args.command == "chat":
        return _run_chat(args)
    if args.command == "doctor":
        return _run_doctor(args)
    if args.command == "session":
        return _run_session(args)

    parser.error(f"Unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
